model {
  file: "model.sdf"
}
name: "Little_Debbie_Cloud_Cakes_10_ct"
description: "Little Debbie Cloud Cakes 10 ct"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Little"
}
annotations {
  key: "gtin"
  value: "00024300044304"
}
annotations {
  key: "sku"
  value: "00024300044304"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
